"""Add payment_method column to Expense

Revision ID: f664f0c77e1a
Revises: ba3bf3f598a2
Create Date: 2025-09-23 21:52:10.568470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f664f0c77e1a'
down_revision: Union[str, Sequence[str], None] = 'ba3bf3f598a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('payment_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'payment_method')
    # ### end Alembic commands ###
